config/routes.rb
Tabletab::Application.routes.draw do

  authenticated :user do
    root :to => 'static_pages#home'
    match '/dashboard', to: 'static_pages#dashboard'
    resources :restaurants
    resources :tables
   
  end
  root :to => "static_pages#home"
  match '/statistics', to: 'static_pages#statistics'
  
  devise_for :users,  :controllers => { :registrations => "users/registrations" }

  resources :users do
    member do
      post 'update_active_restaurant'
    end
  end
  
  resources :menus do
    member do
      post 'save_image'
    end  
  end

  resources :orders #do
  match 'order/:table_id' => 'orders#show_table_for_order'
  post "call_waiter" => "orders#call_waiter", :as => "call_waiter"

  put 'order/:order_id/order_action' => "orders#action_order", :as => "action_order" #:conditions => {:method => :put}

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def dashboard
  	@user = User.find(current_user.id)
  end

  def index
    @users = User.all
  end


  def statistics
  	@restaurant = Restaurant.all
  	@orders = Order.all
  	@orders_nfc = Order.where(:source => "nfc")
  	@orders_qr = Order.where(:source => "QR")

  	my_array =[]

  	@orders.each do |item|
  		diff = (item.close_order_timestamp).to_i - (item.create_order_timestamp).to_i
  		my_array << (diff)
  	end

  	@order_timemax = Time.at(my_array.max).utc.strftime("%H:%M:%S") #=> "01:00:00"
  	@order_timemin = Time.at(my_array.min).utc.strftime("%H:%M:%S") #=> "01:00:00"

  	total = my_array.inject(:+)
  	len = my_array.length
	average = total.to_f / len # to_f so we don't get an integer result
	sorted = my_array.sort
	median = len % 2 == 1 ? sorted[len/2] : (sorted[len/2 - 1] + sorted[len/2]).to_f / 2

  	@order_timeavg = Time.at(average).utc.strftime("%H:%M:%S") #=> "01:00:00"
  	
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/dashboard.html.erb
<div id="dashboard">
	<% if @user.restaurants.any? %>
   	 <% if Restaurant.exists?(@user.activeRestaurant_id) %>
    		<% restaurant = Restaurant.find(@user.activeRestaurant_id) %>
			<h1 id="dashboard"><%= restaurant.name %></h1>
	 <% else %>
			<h1 id="dashboard">Tabletab Dashboard</h1>
	 <% end %>
	<% else %>
		<h1 id="dashboard">Tabletab Dashboard</h1>
	<% end %>

	<p id="dashboard">Use the Dashboard to access the management modules</p>
</div>


<ul id="dashboard">
	<li id="dashboard">
			<%= link_to 'Restaurants   ', restaurants_path , class: "btn  btn-custom" %>
	</li>
	<li id="dashboard">
			<%= link_to 'Tables   ', tables_path, class: "btn btn-custom" %>
	</li>
	<li id="dashboard">
			<%= link_to 'Menu   ', menus_path, class: "btn btn-custom" %>
	</li>
	<li id="dashboard">
			<%= link_to 'Call  waiter list   ', orders_path, class: "btn btn-custom" %>
	</li>
	
</ul>
<br><br><br><br><br><br>
<% if @user.restaurants.any? %>
		
		<p>Click here to <%= link_to "Manage RESTAURANT", restaurants_path %></p>
		
		<%= form_for @user ,  :url => update_active_restaurant_user_path(@user), :html => { :method => :post, :class =>"form-horizontal"} do |f| %>
		<!-- the collection_select method takes the parameters as described below:
			 The :user is the object for the user-table, and the :activeRestaurant_id is the item we 
			want to update in that table.
			The @user.restaurants.all will populate the combobox with the items that are related to 
			only that user. and the :id and :name are the items in the combobox. when an item is selected
			the :activeRestaurant_id will hold the selected :id.
		-->
		<%= collection_select( :user, :activeRestaurant_id , @user.restaurants.all, :id , :name) %>
	  
			  
              <%= f.submit "Submit", :id => "editButton", :class => 'btn-warning btn-primary btn-large' %>
              <br/>
       
		<% end%>

		<p>You have <%= @user.restaurants.count %> registered restaurants</p>
		<p>DEBUG active restaurant is:  <%= @user.activeRestaurant_id %> </p>
<% end %>

app/views/static_pages/home.html.erb
<dl class="dl-horizontal" id="title-bar">
       <dt>
		<%= link_to image_tag("Tabletab-Lesstransparent25.png", alt: "TABLETAB", :height => "50%", :width => "50%", :style => "opacity:0.9", :filter =>"alpha(opacity=99)"), root_path %>
		</dt>
		<dd>
		<h1>Restaurant Management</h1>
	  </dd>
</dl>


<p>
Welcome to the administration module of TableTab. From here you can register and manage your restaurant, your table settings and your menus. It is also here you access the operation module, which you and your staff use to manage the orders received from customers, and download daily, weekly and monthly reports.
</p>
<br><br />
<p>
If you are a new user you can <strong><%= link_to "click here", new_user_registration_path %></strong> to register your restaurant. It is all free initially. When you decide to start using the system with customers you will register for the transaction module separately and choose your plan. Your plan can either be a prepaid fixed monthly fee (plus transactions fee to the chosen payment gateway) or a post paid transaction based fee to TableTab, that is added to the transaction fee payable to the payment gateway.
</p>
<br><br>
<p>
Existing users can access their account by  <strong><%= link_to "clicking here", new_user_session_path %></strong>
  </p>
<br>

<footer class="footer">
  <small>
    <a href="http://www.tabletab.sg/">TABLETAB</a>
    by Mikael Nielsen and Michael Hansen
  </small>
</footer>

app/views/static_pages/statistics.html.erb
<h1>Statistics</h1>

<p>This page displays a simple set of statistics from the system.</P>
<br>
<p>The current information given is the total registration of orders using QR code and NFC chip. Also there will be a total number of restaurant registered during the test and trial run, as well as max, min and average time between order request and waiters action. </p>
<p></p>
<p>Number of restaurants on the system : <%= @restaurant.count %></p>
<p>Total number of orders              : <%= @orders.count %></p>
<p>Number of orders using NFC          : <%= @orders_nfc.count %></p>
<p>Number of orders using QR code      : <%= @orders_qr.count %></p>
<p>Maximum time waited                 : <%= @order_timemax %></p>
<p>Minimum time waited                 : <%= @order_timemin %></p>
<p>Average time waited                 : <%= @order_timeavg %></p>