config/routes.rb
Tabletab::Application.routes.draw do

  authenticated :user do
    root :to => 'static_pages#home'
    match '/dashboard', to: 'static_pages#dashboard'
    resources :restaurants
    resources :tables
   
  end
  root :to => "static_pages#home"
  match '/statistics', to: 'static_pages#statistics'
  
  devise_for :users,  :controllers => { :registrations => "users/registrations" }

  resources :users do
    member do
      post 'update_active_restaurant'
    end
  end
  
  resources :menus do
    member do
      post 'save_image'
    end  
  end

  resources :orders #do
  match 'order/:table_id' => 'orders#show_table_for_order'
  post "call_waiter" => "orders#call_waiter", :as => "call_waiter"

  put 'order/:order_id/order_action' => "orders#action_order", :as => "action_order" #:conditions => {:method => :put}

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :close_order_timestamp, :create_order_timestamp, :produce_order_timestamp, :restaurant_id, :status, :table_id, :status_text, :source, :lon, :lat
 
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  helper_method :call_waiter
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
    @user = User.find(current_user.id)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  def show_table_for_order
      @table = Table.find(params[:table_id])
      @order = Order.new
 #     @menu = Menu.where(:restaurant_id => @table.restaurant_id, :displayonmobilemenu_id => true ).all
      @restaurant = Restaurant.find(@table.restaurant_id)


      render "orders", :layout => 'mobiledevices'
  end

  def action_order
      @order = Order.find(params[:order_id])
      
      if @order
        if @order.status == "2"
          @order.status = "4" # is completed as C
          @order.close_order_timestamp  = Time.zone.now.utc.iso8601()
        end
      end

      if @order.save
        redirect_to :action=>"index"
      end
  end

  def call_waiter
      
        @order = Order.new(params[:order])
        @order.created_at = Time.zone.now.utc.iso8601()
        @order.create_order_timestamp  = Time.zone.now.utc.iso8601()

        #When call waiter is activated the status 
        #send is CW. When its an Order its O.
        #On the server the status will be set to W when its received.
        if @order.status == "CW" #value send from mobile
          @order.status = "2"     #setting the status to Waiting
        end

        tableid = @order.table_id

        # lets see if its a QR code or NGC chip the cal came from
        # Create the URL to return to the same page
        # at the same time we detect how the URL was detected from the device QR or NFC
        if @order.source == "nfc"
          @url = url_for :controller => 'orders', :action => 'show_table_for_order', :table_id => tableid, :source => :nfc
        elsif @order.source == ""
          @url = url_for :controller => 'orders', :action => 'show_table_for_order', :table_id => tableid
          @order.source = "QR"
        end
        current_url =  @url
        
        if @order.lat != ""  
          #'http://0.0.0.0:3000/order/5'
          if @order.save
            respond_to do |format|
              format.html { redirect_to( current_url )}
              format.js { redirect_to( orders_url)}#{ render "orders", :layout=>'mobiledevices' } 
            end
          end
        end
  end
  
 # def new
 #      @order = Orders.new
 # end
  
 # def create
 #   @order = Orders.new(params[:table_id])
 #   if @order.save
      # flash[:success] = "Welcome to TABLETAB "
      #redirect_to root_url, :notice => "Signed up!" 
      #redirect_to @user
 #     gflash :notice => { :value => "The Order was saved in our database !", :time => 4000 } 
 #   else
 #     render "orders"
 #   end
 # end


  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

#    respond_to do |format|
#      if @order.save
#        format.html { redirect_to @order, notice: 'Order was successfully created.' }
#        format.json { render json: @order, status: :created, location: @order }
#      else
#        format.html { render action: "new" }
#        format.json { render json: @order.errors, status: :unprocessable_entity }
#      end
#    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= simple_form_for(@order) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :restaurant_id %>
    <%= f.input :table_id %>
    <%= f.input :status %>
    <%= f.input :create_order_timestamp %>
    <%= f.input :produce_order_timestamp %>
    <%= f.input :close_order_timestamp %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/orders/call_waiter.js.erb
$('#clockDisplay').html('<%= escape_javascript(render :text => "Waiting for waiter: #{Time.now.utc.getlocal.strftime("%I:%M%p")}") %>')

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<%= link_to 'New Order (will only be visible to admin)', new_order_path %>
<meta http-equiv="refresh" content="10" />
<div class="order-page">
   
    <div id="top-info" class="row">
        <div class="span3">
            <% if @user.restaurants.any? %>
                <% if Restaurant.exists?(@user.activeRestaurant_id) %>
                    <% restaurant = Restaurant.find(@user.activeRestaurant_id) %>
                    <h1 id="Restaurant-status"><%= restaurant.name %></h1>
                <% else %>
                    <h1 id="Restaurant-status">You must select a restaurant</h1>
                <% end %>
            <% else %>
                <h1 id="Restaurant-status">You must select a restaurant</h1>
            <% end %>
        </div>
        <div class="span4 offset4">
                <div id="clockDisplay" class="timeStyle"></div>
        </div>

    </div>
    <div id="icon-panel" class="row">
        <div id="Wait-icon" class="span1 offset6"><p id="Wait-icon">W</p></div>
        
        <div id="Process-icon" class="span1"><p id="Process-icon">P</p></div>
        
        <div id="Ready-icon" class="span1"><p id="Ready-icon">R</p></div>
        
        <div id="Close-icon" class="span1"><p id="Close-icon">C</p></div>
    </div>
    
<div id="order-list">
        <!-- We only want to display for the active restaurant  (the code should be moved to the controller) -->
        <% @myorders = Order.where(:restaurant_id => current_user.activeRestaurant_id).order("status ASC, create_order_timestamp ASC") %>
        <% @myorders.each do |order| %> 
          <% tablenumber = Table.find(order.table_id).tablenumber %>
    
          
            <!-- td><%= order.restaurant_id %></td -->
            <div class="row" id="order-row">
                <%= link_to action_order_path(order), :method => :put do%>
                <span>
                    <% if order.status == "2" %>
                        <div id="Wait-icon" class="span1"><p id="Wait-icon">W</p></div>
                    <% elsif order.status == "1" %>
                        <div id="Process-icon" class="span1"><p id="Process-icon">P</p></div>
                    <% elsif order.status == "3" %>
                        <div id="Ready-icon" class="span1"><p id="Ready-icon">R</p></div>
                    <% elsif order.status == "4" %>
                        <div id="Close-icon" class="span1"><p id="Close-icon">C</p></div>
                    <% end %>
                
                    <div class="span3">
                        <h2 class="item-title">
                            To Do
                        </h2>
                        <h2 class="item-text-title">
                            <%= order.status_text %>
                        </h2>
                    </div>
                    <div class="span2">
                        <h2 class="tablenumber-title">
                            Table number
                        </h2>
                        <h1 class="tablenumber-text">
                             <%= tablenumber %>
                         </h1>
                    </div>
                    
                    <div class="span3">
                        <p>
                            Ordered at 
                            <% tz = TZInfo::Timezone.get(@user.time_zone) %>
                            <% if order.create_order_timestamp %>
                                <% local = tz.utc_to_local(Time.at(order.create_order_timestamp.to_i)) %>
                                <%= local.strftime("%I:%M:%S%p") %>
                             <% end %>
                        </P>

                        <ul class="order-time-list">
                          <p>Device source is :<%= order.source %></p>   
                            
                        </ul>
                    </div> <!-- order-time -->

                    <div class="action-buttons">
                            <!-- %= link_to 'Show', order % -->
                            <!-- %= link_to 'Edit', edit_order_path(order) % -->
                            <!-- %= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } % -->
                    </div>
                </span>
                <% end %>
            </div> <!-- row-->   
            <div class="divspacer"></div>
             
            <% end %>
</div> <!-- order-list -->
</div> <!-- order-page -->
<script type="text/javascript" language="javascript">
    function renderTime() {
        var currentTime = new Date();
        var diem = "AM";
        var h = currentTime.getHours();
        var m = currentTime.getMinutes();
        var s = currentTime.getSeconds();
        
        if (h == 0) {
            h == 12;
        } else if (h > 12) {
            h = h - 12;
            diem = "PM";
        }
        if (h < 10){
            h ="0" + h;
        }
        if (m < 10){
            m ="0" + m;
        }
        if (s < 10){
            s ="0" + s;
        }

        var myClock = document.getElementById('clockDisplay');
         //firefox
        myClock.textContent = h + ":" + m + ":" + s + " " + diem;
        // IE
        myClock.innerText = h + ":" + m + ":" + s + " " + diem;
        

        setTimeout('renderTime()', 1000);
    }
    renderTime();
</script>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/orders.html.erb
<div id="mobiledevice">
<input type="hidden" id="geofence_radius" name="geofence_radius" value=<%=  @restaurant.geofence_radius %> >
<h1 class="mobile_device"><%= @restaurant.name %>
</h1>
<p>Table number: <%= @table.tablenumber %>
</p>


<div id = "clockDisplay"></div>
<!-- p>  	
	Tableid: <%= @table.id %>
</p -->
<p><%= params[:source] %> </p>
<% if @restaurant.currency_id != "THB" 
     @button_string = "Call Waiter"
     @menu_string = "Menu"
    else
     @button_string = "เรียกบริกร" 
     @menu_string = "เมน"
   end %>

<%= form_for(@order, :url => url_for(:controller => "orders", :action => "call_waiter" ) ,:html => {:multipart => true} ) do |f| %>    <!-- , :remote => true  -->                   
	<%= f.hidden_field :table_id, :value => @table.id %>
	<%= f.hidden_field :restaurant_id, :value => @restaurant.id %>
    <%= f.hidden_field :status_text, :value => "Call waiter" %>
    <%= f.hidden_field :status, :value => "CW" %>  <!-- When call waiter is activated the status 
    													send is CW. When its an Order its O.
    													On the server the status will be set to W when its received. -->
    <%= f.hidden_field :create_order_timestamp, :value => Time.now.utc.iso8601()  %>
    <%= f.hidden_field :source, :value => params[:source]  %>
    <%= f.hidden_field :lat, :value => params[:lat] %>
    <%= f.hidden_field :lon, :value => params[:lon] %>
    <div id ="data"></div><!-- this should be removed due as it was used to hold debug info about location -->

	<%= f.submit @button_string, :id => "css3dbutton", :disable_with => 'Saving...' %>
<% end %>

<!-- Add in the menu here -->
<% if @restaurant.display_menu_on_mobile == true %>
<div><pre id="menu"> <!-- style="background-color: black;" -->
  <%= @restaurant.restaurant_message %>
  </pre>
</div>

<center>
<div id="menublok">
  
  <h1 id="menuhead"><%= @menu_string %></h1> 
  <table id="menulist">
  <% @menus = Menu.where(:restaurant_id => @restaurant.id) %>
        <% @menus.each do |menu| %>
          <tr> <td id="menutitle"><%= menu.title %></td>
              <% Money.default_currency = Money::Currency.new(@restaurant.currency_id) %>
               <td id="price"><%= humanized_money_with_symbol menu.price %></td>
          </tr>
          <tr>
            <td id="description" colspan="2"><em><%= menu.description %></em></td>
          </tr>
          <tr>
            <td id="description" colspan="2"><em><p></p></em></td>
          </tr>
        <% end %>
  </table>


  <% end %>
  </div>
</center>

</div> <!-- mobiledevice -->


<script>

var myPosition = new Array();

$(document).ready(function() {

     navigator.geolocation.getCurrentPosition(
             onSuccess,
             onError, {
                 enableHighAccuracy: true,
                 timeout: 20000,
                 maximumAge: 120000
             }
     );
   function onSuccess(position) {
       myPosition[0] = position.coords.latitude;
       myPosition[1] = position.coords.longitude;

       var data = '';
   
  data += 'latitude: ' + position.coords.latitude + '<br/>';
  data += 'longitude: ' + position.coords.longitude + '<br/>';
  // data += 'altitude: ' + position.coords.altitude + '<br/>';
  // data += 'accuracy: ' + position.coords.accuracy + '<br/>';
  // data += 'altitudeAccuracy: ' + position.coords.altitudeAccuracy + '<br/>';
  // data += 'heading: ' + position.coords.heading + '<br/>';
  // data += 'speed: ' + position.coords.speed + '<br/>';
  //document.getElementById('order_lat').value = position.coords.latitude;
  //document.getElementById('order_lon').value = position.coords.longitude;
  //document.getElementById('data').innerHTML = data;
  //loadMap(position.coords.latitude, position.coords.longitude);
  testGeofence( position.coords.latitude, position.coords.longitude, <%= @restaurant.lat %>, <%= @restaurant.lon %>, <%= @restaurant.geofence_radius %> );
   }

    function onError(err) {
       var message;

       switch (err.code) {
       case 0:
         message = 'Unknown error: ' + err.message;
         break;
       case 1:
         message = 'You denied permission to retrieve a position.';
         break;
       case 2:
         message = 'The browser was unable to determine a position: ' + error.message;
         break;
       case 3:
         message = 'The browser timed out before retrieving the position.';
         break;
       }
    }






});

function getDistance(lat1, lon1, lat2, lon2) {
    //Radius of the earth in:  1.609344 miles,  6371 km  | var R = (6371 / 1.609344);
    var R = 6371; // Radius of earth in Kilometers x 1000 to get meters
    var dLat = toRad(lat2-lat1);
    var dLon = toRad(lon2-lon1); 
    var a = Math.sin(dLat/2) * Math.sin(dLat/2) +
            Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * 
            Math.sin(dLon/2) * Math.sin(dLon/2); 
    var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a)); 
    var d = (R*1000) * c;
    return d;
}

function toRad(Value) {
    /** Converts numeric degrees to radians */
    return Value * Math.PI / 180;
}

function testGeofence($latitude1, $longitude1, $latitude2, $longitude2, $geofence_radius )
{
  $distance = getDistance( $latitude1, $longitude1, $latitude2, $longitude2);
  if( $distance < ($geofence_radius) ){ // in meters so geofence is in meters
      document.getElementById('css3dbutton').value= <%= @button_string %>;
  } else {
     document.getElementById('css3dbutton').value="Order not allowed";
     document.getElementById('css3dbutton').style.display = "none";
  }
}
</script>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Restaurant:</b>
  <%= @order.restaurant_id %>
</p>

<p>
  <b>Table:</b>
  <%= @order.table_id %>
</p>

<p>
  <b>Status:</b>
  <%= @order.status %>
</p>

<p>
  <b>Create order timestamp:</b>
  <%= @order.create_order_timestamp %>
</p>

<p>
  <b>Produce order timestamp:</b>
  <%= @order.produce_order_timestamp %>
</p>

<p>
  <b>Close order timestamp:</b>
  <%= @order.close_order_timestamp %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>