config/routes.rb
Tabletab::Application.routes.draw do

  authenticated :user do
    root :to => 'static_pages#home'
    match '/dashboard', to: 'static_pages#dashboard'
    resources :restaurants
    resources :tables
   
  end
  root :to => "static_pages#home"
  match '/statistics', to: 'static_pages#statistics'
  
  devise_for :users,  :controllers => { :registrations => "users/registrations" }

  resources :users do
    member do
      post 'update_active_restaurant'
    end
  end
  
  resources :menus do
    member do
      post 'save_image'
    end  
  end

  resources :orders #do
  match 'order/:table_id' => 'orders#show_table_for_order'
  post "call_waiter" => "orders#call_waiter", :as => "call_waiter"

  put 'order/:order_id/order_action' => "orders#action_order", :as => "action_order" #:conditions => {:method => :put}

end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
 helper_method :qr_code

  def qr_code(size, url)
      #@qr = RQRCode::QRCode.new(url)
  end

  # GET /tables
  # GET /tables.json
  def index
    if Table.exists?(current_user.activeRestaurant_id)
     @tables = Table.all
    else
      @tables = 0 
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tables }
    end
  end

  # GET /tables/1
  # GET /tables/1.json
  def show
    @table = Table.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @table }
    end
  end

  # GET /tables/new
  # GET /tables/new.json
  def new
    @table = Table.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @table }
    end
  end

  # GET /tables/1/edit
  def edit
    @table = Table.find(params[:id])
  end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(params[:table])

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: 'Table was successfully created.' }
        format.json { render json: @table, status: :created, location: @table }
      else
        format.html { render action: "new" }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tables/1
  # PUT /tables/1.json
  def update
    @table = Table.find(params[:id])

    respond_to do |format|
      if @table.update_attributes(params[:table])
        format.html { redirect_to @table, notice: 'Table was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table = Table.find(params[:id])
    @table.destroy

    respond_to do |format|
      format.html { redirect_to tables_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/tables/_form.html.erb
<%= simple_form_for(@table) do |f| %>
  <%= f.error_notification %>

  <%= f.hidden_field :restaurant_id, :value => current_user.activeRestaurant_id %>
  <% if @table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@table.errors.count, "error") %> prohibited this table from being saved:</h2>
        <ul>
          <% @table.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <%= f.input :tablenumber %>
    <%= f.input :tablename %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/tables/edit.html.erb
<h1>Editing table</h1>

<%= render 'form' %>

<%= link_to 'Show', @table %> |
<%= link_to 'Back', tables_path %>

app/views/tables/index.html.erb
<h1>Listing tables</h1>

  <table>
   <tr>
     
     <th>Tablename</th>
     <th>Tablenumber</th>
     <th></th>
     <th></th>
     <th></th>
    </tr>
    <% if @tables %>
      <% @mytables = Table.where(:restaurant_id => current_user.activeRestaurant_id) %>
      <% @mytables.each do |table| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
         <td class="list_description"><%= table.tablename %></td>
         <td><%= table.tablenumber %></td>
         <td> 
            <!-- %= qr_code (10, request.url) % -->
            <%  @url = url_for :controller => 'orders', :action => 'show_table_for_order', :table_id => table.id  %>
            <%= @final_URL = "#{request.scheme}://#{request.host_with_port}" + @url %>
            <%= image_tag "https://chart.googleapis.com/chart?chs=150x150&cht=qr&chl=#{@final_URL}&choe=UTF-8" %>
            <%  @nfc_url = url_for :controller => 'orders', :action => 'show_table_for_order', :table_id => table.id, :source => :nfc  %>
            <%= @final_NFC_URL = "#{request.scheme}://#{request.host_with_port}" + @nfc_url %>
         </td>
         <td><%= link_to 'Show', table %></td>
         <td><%= link_to 'Edit', edit_table_path(table) %></td>
         <td><%= link_to 'Destroy', table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
       </tr>
      <% end %>
    <% end %>
  </table>

<br />

<%= link_to 'New Table', new_table_path %>

app/views/tables/new.html.erb
<h1>New table</h1>

<%= render 'form' %>

<%= link_to 'Back', tables_path %>

app/views/tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tablenumber:</b>
  <%= @table.tablenumber %>
</p>

<p>
  <b>Tablename:</b>
  <%= @table.tablename %>
</p>

<p>
  <b>Restaurant:</b>
  <%= @table.restaurant_id %>
</p>


<%= link_to 'Edit', edit_table_path(@table) %> |
<%= link_to 'Back', tables_path %>