config/routes.rb
Tabletab::Application.routes.draw do

  authenticated :user do
    root :to => 'static_pages#home'
    match '/dashboard', to: 'static_pages#dashboard'
    resources :restaurants
    resources :tables
   
  end
  root :to => "static_pages#home"
  match '/statistics', to: 'static_pages#statistics'
  
  devise_for :users,  :controllers => { :registrations => "users/registrations" }

  resources :users do
    member do
      post 'update_active_restaurant'
    end
  end
  
  resources :menus do
    member do
      post 'save_image'
    end  
  end

  resources :orders #do
  match 'order/:table_id' => 'orders#show_table_for_order'
  post "call_waiter" => "orders#call_waiter", :as => "call_waiter"

  put 'order/:order_id/order_action' => "orders#action_order", :as => "action_order" #:conditions => {:method => :put}

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  attr_accessible :city, :country, :display_menu_on_mobile, :name, :currency_id, :phone, :restaurant_size, :restaurant_message, :state, :street, :user_id, :zip, :lon, :lat, :geofence_radius
  
  attr_accessor :geo_update_from_map

  belongs_to :user
  validates :user_id, presence: true
  has_many :tables

 

# Geocoder is used with bing
  geocoded_by :address, :latitude  => :lat, :longitude => :lon  do |restaurant, results| # ActiveRecord
  	if @geo_update_from_map == false
      if geo = results.first
    	 restaurant.lat = geo.latitude
    	 restaurant.lon = geo.longitude
  	  end
    end
  end

  before_validation :geocode          # auto-fetch coordinates

def address
  [street, city, country].compact.join(', ')
end

def geo_update_from_map
  self.geo_update_from_map
end
#def initialize
#  @geo_update_from_map = false
#end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @restaurants }
    end
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @restaurant = Restaurant.find(params[:id])
    @restaurant.geo_update_from_map = false 

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @restaurant }
    end
  end


def major_currencies(hash)
  hash.inject([]) do |array, (id, attributes)|
    priority = attributes[:priority]
    if priority && priority < 10
      array[priority] ||= []
      array[priority] << id
    end
    array
  end.compact.flatten
end

# Returns an array of all currency id
def all_currencies(hash)
  hash.keys
end

  # GET /restaurants/new
  # GET /restaurants/new.json
  def new
    @restaurant = Restaurant.new
    
    # preparing the form select for the currencies
     @currencies = [] 
     all_currencies(Money::Currency.table).each do |currency|  
       name = Money::Currency.table[currency][:name]
       iso_code = Money::Currency.table[currency][:iso_code]
       @currencies << [name, iso_code]
     end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @restaurant }
    end
  end

  # GET /restaurants/1/edit
  def edit
    @restaurant = Restaurant.find(params[:id])

    # preparing the form select for the currencies
     @currencies = [] 
     all_currencies(Money::Currency.table).each do |currency|  
       name = Money::Currency.table[currency][:name]
       iso_code = Money::Currency.table[currency][:iso_code]
       @currencies << [name, iso_code]
     end
  end

  #currently not used as this was written for the geocoder - 
  #perhaps if we solve the server lookup we can use this
  def update_geo_location (restaurant)
    if restaurant.street != "" && restaurant.city != "" && restaurant.country != ""
      searchString = restaurant.street+","+restaurant.city+","+restaurant.country
      #s = Geocoder.coordinates(searchString)
      s = Geocoder.coordinates(searchString)
      #if s
        restaurant.lat = s[0].to_f
        restaurant.lon = s[1].to_f
      #end
    end 
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(params[:restaurant])
    @restaurant.geo_update_from_map = false

    update_geo_location (@restaurant)


    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render json: @restaurant, status: :created, location: @restaurant }
      else
        format.html { render action: "new" }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /restaurants/1
  # PUT /restaurants/1.json
  def update
    @restaurant = Restaurant.find(params[:id])

     #update_geo_location (@restaurant)
    @restaurant.geo_update_from_map = false  

    respond_to do |format|
      if @restaurant.update_attributes(params[:restaurant])
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    respond_to do |format|
      format.html { redirect_to restaurants_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :street %>
    <%= f.input :city %>
    <%= f.input :state %>
    <%= f.input :zip %>
    <%= f.input :country %>
    <%= f.input :geofence_radius %>
    <%= f.input :phone %>
    <%= f.input :restaurant_size %>
    <%= f.select(:currency_id, @currencies) %>
    <!-- %= f.input :currency_id % -->
    <%= f.input :restaurant_message %>
    <%= f.input :display_menu_on_mobile %>
    
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/_form_update.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :street %>
    <%= f.input :city %>
    <%= f.input :state %>
    <%= f.input :zip %>
    <%= f.input :country %>
    <%= f.input :lon %>
    <%= f.input :lat %>
    <%= f.input :geofence_radius %>
    <%= f.input :phone %>
    <%= f.input :restaurant_size %>
    <%= f.select(:currency_id, @currencies) %>
    <!-- %= f.input :currency_id % -->
    <%= f.input :restaurant_message %>
    <%= f.input :display_menu_on_mobile %>
    
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>
<style type="text/css">
        #map_canvas {height:450px;width:300px}
</style>
<script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyAXZZSH82tHV6fVvEu94ZSQySXwfy8-yoM&sensor=false">
</script>


<script type="text/javascript">
  var map;
  var markersArray = [];
  var marker;
  var cityCircle;
  var circleON;

  var latlng = new google.maps.LatLng(<%= @restaurant.lat %>, <%= @restaurant.lon %>);

  var sunCircle = {
        strokeColor: "#c3fc49",
        strokeOpacity: 0.8,
        strokeWeight: 2,
        fillColor: "#c3fc49",
        fillOpacity: 0.35,
        map: map,
        center: latlng,
        radius: 100 // in meters
    };

function setRadius() {
  r = document.getElementById("restaurant_geofence_radius").value;
  sunCircle.setRadius(r);
  document.getElementById("test").value = r;
}

function toggleCircle(){
  if (circleON){
    circleON = false;
    cityCircle.setMap(null);
  } else {
    circleON = true;
    sunCircle.radius = parseFloat(document.getElementById("restaurant_geofence_radius").value);
    cityCircle = new google.maps.Circle(sunCircle);   
    cityCircle.setMap(map);
    cityCircle.bindTo('center', marker, 'position');
  }
}

function initialize() {
    var mapOptions = {
        center: latlng,
        zoom: 16,
        mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    var el=document.getElementById("map_canvas");
    circleON = true;
    map = new google.maps.Map(el, mapOptions);

    //var marker = new google.maps.Marker({
    //    map: map,
    placeMarker(latlng);
    //});
    google.maps.event.addListener(marker, 'drag', function(event){
        document.getElementById("restaurant_lat").value = event.latLng.lat();
        document.getElementById("restaurant_lon").value = event.latLng.lng();
    });
    cityCircle = new google.maps.Circle(sunCircle);   
    sunCircle.radius = parseFloat(<%= @restaurant.geofence_radius %>);
    cityCircle.setMap(map);
    cityCircle.bindTo('center', marker, 'position');   
}

function placeMarker(location) {
            // first remove all markers if there are any
            deleteOverlays();

            marker = new google.maps.Marker({
                position: location, 
                draggable: true,
                map: map
            });

            // add marker in markers array
            markersArray.push(marker);

        }

        // Deletes all markers in the array by removing references to them
        function deleteOverlays() {
            if (markersArray) {
                for (i in markersArray) {
                    markersArray[i].setMap(null);
                }
              markersArray.length = 0;
            }
        }


window.onload = google.maps.event.addDomListener(window, 'load', initialize);

    </script>

    <p>
<%= button_tag "View on map",:id => "map_button", :onCLick =>"initialize()" %>
<%= button_tag "Toggle geofence",:id => "geo_button", :onCLick =>"toggleCircle()" %>



<div id="map_canvas" style="width:450px;height:300px;"></div>
</p>
<%= render 'form_update' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Listing restaurants</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Street</th>
    <th>City</th>
    
    <th>Phone</th>
   
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @restaurants = Restaurant.where(:user_id => current_user.id) %>
<% @restaurants.each do |restaurant| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    <td class="list_description"><%= restaurant.name %></td>
    <td><%= restaurant.street %></td>
    <td><%= restaurant.city %></td>
   
    <td><%= restaurant.phone %></td>
    
    <td><%= link_to 'Show', restaurant %></td>
    <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
    <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @restaurant.name %>
</p>

<p>
  <b>Street:</b>
  <%= @restaurant.street %>
</p>

<p>
  <b>City:</b>
  <%= @restaurant.city %>
</p>

<p>
  <b>State:</b>
  <%= @restaurant.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @restaurant.zip %>
</p>

<p>
  <b>Country:</b>
  <%= @restaurant.country %>
</p>

<p>
  <b>Phone:</b>
  <%= @restaurant.phone %>
</p>

<p>
  <b>Restaurant size:</b>
  <%= @restaurant.restaurant_size %>
</p>

<p>
  <b>Currency:</b>
  <%= @restaurant.currency_id %>
</p>

<p>
  <b>Restaurant Message:</b>
  <%= @restaurant.restaurant_message %>
</p>

<p>
  <b>Display on mobile:</b>
  <%= @restaurant.display_menu_on_mobile %>
</p>

<p>
  <b>User:</b>
  <%= @restaurant.user_id %>
</p>


<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>